version: "3"
services:
  database:
    container_name: database
    restart: always
    image: postgres:12.7-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    container_name: django_backend
    restart: always
    image: hpharipriya/loan-app
#    build: .
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - Q_URL=${Q_URL}

    volumes:
      - ./:/app
    depends_on:
      - database
#    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn -b 0.0.0.0:8000 core.wsgi"

  nginxrp:
    container_name: nginxrp
    restart: always
#    build: ./nginx-server
    image: hpharipriya/loan-nginx
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./staticfiles:/staticfiles

  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3.9-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq


  queue_worker:
    container_name: queue_worker
    restart: always
#    build:
#      context: ./worker
#      dockerfile: Dockerfile
    image: hpharipriya/loan-worker
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - Q_URL=${Q_URL}
    volumes:
      - ./worker:/app
    depends_on:
      - rabbitmq
      - database

#    command: python worker.py

  bank_api_1:
    container_name: bank_api_1
    image: lendoab/interview-service:stable
    ports:
      - 8081:8000
  bank_api_2:
    container_name: bank_api_2
    image: lendoab/interview-service:stable
    ports:
      - 8082:8000
  bank_api_3:
    container_name: bank_api_3
    image: lendoab/interview-service:stable
    ports:
      - 8083:8000

volumes:
  db_data:
  rabbitmq_data: