# Generated by Django 4.0.6 on 2022-07-18 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('rejected', 'rejected')], default='Pending', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.DeleteModel(
            name='BankApplications',
        ),
        migrations.AddField(
            model_name='bankapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.application'),
        ),
        migrations.AddField(
            model_name='bankapplication',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.bank'),
        ),
    ]
